name: Code tests & eval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all:
    name: Build all variants
    strategy:
      fail-fast: false
      matrix:
        flavor: [ Foss,Gplay ]
        variant: [ Debug,Beta,Release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ${{ matrix.variant }} + ${{ matrix.flavor }}
        run: ./gradlew assemble${{ matrix.variant }}${{ matrix.flavor }}

  test-all:
    name: Run all tests
    strategy:
      fail-fast: false
      matrix:
        flavor: [ Foss,Gplay ]
        variant: [ Debug,Beta,Release ]
        modules: [ app,app-common,app-common-io,app-common-pkgs,app-common-root,app-common-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Google Play variant
        run: ./gradlew ${{ matrix.modules }}:test${{ matrix.flavor }}${{ matrix.variant }}UnitTest